[package]
name = "adguard-to-url-cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
regex-syntax = "0.8.3"
thiserror = "1.0.59"
url-cleaner = { path = "../url-cleaner" }
